/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as MediaRangeFilenameRouteImport } from './routes/media-range/$filename'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRangeFilenameRoute = MediaRangeFilenameRouteImport.update({
  id: '/media-range/$filename',
  path: '/media-range/$filename',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/contact': typeof ApiContactRoute
  '/media-range/$filename': typeof MediaRangeFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/contact': typeof ApiContactRoute
  '/media-range/$filename': typeof MediaRangeFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/contact': typeof ApiContactRoute
  '/media-range/$filename': typeof MediaRangeFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/contact' | '/media-range/$filename'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/contact' | '/media-range/$filename'
  id: '__root__' | '/' | '/api/contact' | '/media-range/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiContactRoute: typeof ApiContactRoute
  MediaRangeFilenameRoute: typeof MediaRangeFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-range/$filename': {
      id: '/media-range/$filename'
      path: '/media-range/$filename'
      fullPath: '/media-range/$filename'
      preLoaderRoute: typeof MediaRangeFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiContactRoute: ApiContactRoute,
  MediaRangeFilenameRoute: MediaRangeFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
